name: Linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install lint dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff black
      - name: Ruff
        run: ruff check sklekmeans examples
      - name: Black
        run: black --check sklekmeans examples
